### Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [1]:
import numpy as np

In [4]:
inp_vector = np.array([1, 2, 3, 5])
inp_vector

array([1, 2, 3, 5])

In [55]:
def Vandermonde_fn(inp_vector, N, increasing = False):
    if increasing:
        return np.column_stack([inp_vector**(N - i - 1) for i in reversed(range(N))])
    else:
        return np.column_stack([inp_vector**(N - i - 1) for i in range(N)])


In [60]:
print("When increasing is true :")
Vandermonde_fn(inp_vector, 3, True)

When increasing is true :


array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]], dtype=int32)

In [61]:
print("When increasing is False :")
Vandermonde_fn(inp_vector, 3, False)

When increasing is False :


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of 
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100 
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.Question: Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [52]:
n=10
Seq = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3

In [53]:
def moving_average(arr,k):
    n= len(arr)
    for i in range(n-k+1):
        ma_value = 0
        for m in range(k):
            ma_value = float(ma_value + arr[i+m])
        ma_value = ma_value/k
        print("y",str(i+1),"=",str(ma_value))

In [54]:
moving_average(Seq,k)

y 1 = 5.0
y 2 = 4.666666666666667
y 3 = 5.666666666666667
y 4 = 6.666666666666667
y 5 = 9.666666666666666
y 6 = 28.666666666666668
y 7 = 49.333333333333336
y 8 = 72.66666666666667
y 9 = 84.0
y 10 = 93.33333333333333
y 11 = 116.33333333333333
